### ISSUE TITLE
Traditional gr2 files?

### ISSUE THREAD

**Issue by tin2tin** [SWTOR-Slicers/Granny2-Plug-In-Blender-2.8x#3]
As this seems to be the only gr2 exporter for Blender, and the SWTOR variant files doesn't seem to be imported in traditional gr2 reading applications, do you know where I can find descriptions on the variations?

**Comment by ZeroGravitasIndeed** [comment]
There is one such in our wiki. You can read it here: [GR2 File Structure](https://github.com/SWTOR-Slicers/WikiPedia/wiki/GR2-File-Structure).

**Comment by ZeroGravitasIndeed** [comment]
> As this seems to be the only gr2 exporter for Blender, and the SWTOR variant files doesn't seem to be imported in traditional gr2 reading applications, do you know where I can find descriptions on the variations?

There is one such in our wiki. You can read it here: [GR2 File Structure](https://github.com/SWTOR-Slicers/WikiPedia/wiki/GR2-File-Structure).

**Comment by tin2tin** [comment]
Thank you. Do you know if swtor gr2 files should be possible to import in Granny?
