### ISSUE TITLE
Whats the licence?

### ISSUE THREAD

**Issue by stumpy1029** [SWTOR-Slicers/Granny2-Plug-In-Blender-2.8x#5]
Can I use this in my own blender plugin for modding the game Halo Wars: DE? I will include proper credits. This would save me a whole lot of time!

**Comment by Tormak9970** [comment]
> Can I use this in my own blender plugin for modding the game Halo Wars: DE? I will include proper credits. This would save me a whole lot of time!

It likely would not work. this is SWTOR proprietary format. Even if the file name is .gr2 its not actually the same format

**Comment by stumpy1029** [comment]
Can I mess with it and release it if it works for my use case?

**Comment by stumpy1029** [comment]
Even having the granny_file header would save me a lot of time

**Comment by Tormak9970** [comment]
I am not the original creator of the plugin. @LeeThorogood will need to answer that. By default the answer is you can't use it for anything btw

**Comment by StarLight-Oliver** [comment]
I know nothing about the Halo file format. But each version of gr2 tends to be very different and this is unlikely to help.
